tickets/admin.py
users/admin.py

Add Admin Setting of Ticket and Users

---

games/admin.py
games/apps.py
games/models.py
games/tests.py
games/views.py
kboBack/settings.py

경기 일정, 팀, 구장 정보를 담을 Games APP 생성

Create Games App

---

users/tests.py
users/urls.py
users/views.py

비밀번호 수정, 팀 변경
비밀번호 수정, 팀 변경
확인 부탁드립니다

비밀번호 수정, 팀 변경

---

requirements.txt
users/selectors.py
users/services.py
users/urls.py
users/views.py

Make UserLoginAPI

---

users/services.py
users/views.py

API 명세에 맞춰 User Login의 return 데이터셋 변경

Modity User Login Output Data

---

kboBack/settings.py
requirements.txt
tickets/models.py
tickets/views.py

Modfy Ticket's information

---

backend/apis/urls.py
backend/conf/settings.py
backend/conf/urls.py
backend/requirements.txt

- KBOBACK-31
- Swagger 추가
- 없음

[KBOBACK-31] Swagger 추가

---

backend/apis/auths/serializers.py
backend/apis/auths/services.py
backend/apis/auths/utils.py
backend/apis/auths/views.py
backend/base/authentication.py
backend/conf/settings/base.py

[KBOBACK-46] 세션 로그인 제거 및 revoke, refresh 추가

---

backend/Dockerfile
backend/conf/settings/docker.py
backend/config_example.toml
backend/pyproject.toml
docker-compose.yml

- KBOBACK-49
- poetry 적용에 따른 도커 관련 설정 수정
- 없음

[KBOBACK-49] poetry 적용에 따른 도커 관련 설정 수정

---

docker-compose.yml

[KBOBACK-46-FIX] docker-compose 파일 수정

---

backend/config_example.toml
backend/scripts/init_script.py

[KBOBACK-46-FIX3] 설정 파일 추가 수정

---

backend/apis/notifications/urls.py
backend/apis/notifications/views.py
backend/apis/urls.py
backend/apps/notifications/__init__.py
backend/apps/notifications/admin.py
backend/apps/notifications/config.py
backend/apps/notifications/models.py
backend/conf/settings/base.py

-  KBOBACK-60
- notification 앱 신규 추가
- modeling
- 기존 alert에서 notification으로 네이밍 변경했습니다. 리뷰가 필요합니다!

[KBOBACK-60] Notification 모델링

---

backend/apis/users/serializers.py
backend/apis/users/services.py
backend/apis/users/views.py

- KBOBACK-66
- 친구 초대 코드 관련 추가 작업
- 없음

[KBOBACK-66] 친구 추가 API 관련 부가 작업 진행

---

backend/apis/users/serializers.py
backend/apis/users/services.py
backend/apis/users/views.py

- KBOBACK-71
- 회원 탈퇴 API 추가
- 없음

[KBOBACK-71] 회원 탈퇴 API 추가

---

backend/apis/users/serializers.py
backend/apis/users/swagger.py
backend/apis/users/views.py
backend/conf/settings/base.py

- KBOBACK-83
- 스웨어 추가 및 인증 헤더 모달 변경
- 없음

[KBOBACK-83] 스웨어 추가 및 인증 헤더 모달 변경

---

backend/apis/teams/serializers.py
backend/apis/teams/views.py
backend/apis/users/services.py

- KBOBACK-90
- 팀관련 API 정리 및 유저 정보 변경 API 수정
- 없음

[KBOBACK-90] 팀관련 API 정리 및 유저 정보 변경 API 수정

---

backend/apis/games/swagger.py

-  feature/KBOBACK-92
- games list api swagger 수정
-

feature/KBOBACK-92 - games api 수정

---

backend/apis/users/serializers.py
backend/apis/users/swagger.py
backend/apis/users/views.py

- KBOBACK-97
- 친구 목록 조회(티켓 포함) API 추가
- 없음

[KBOBACK-97] 친구 목록 조회(티켓 포함) API 추가

---

backend/apis/auths/serializers.py
backend/apis/auths/services.py
backend/apis/auths/swagger.py
backend/apis/auths/views.py
backend/conf/settings/base.py
backend/config_example.toml
backend/poetry.lock
backend/pyproject.toml

[KBOBACK-84] 애플 로그인 추가

---

backend/apis/games/views.py

[KBOBACK-84] game list view pagination delete

---

backend/apis/alerts/views.py
backend/apis/auths/views.py
backend/apis/games/views.py
backend/apis/notifications/views.py
backend/apis/teams/views.py
backend/apis/tickets/views.py
backend/apis/uploads/views.py
backend/apis/users/views.py
backend/base/middlewares.py
backend/base/mixins.py
backend/conf/settings/base.py
backend/config_example.toml
backend/poetry.lock
backend/pyproject.toml

- KBOBACK-107
- 센트리 로깅 전역에 적용
- 없음

[KBOBACK-107] 센트리 로깅 전역에 적용

---

backend/apis/teams/swagger.py
backend/apis/teams/views.py

[KBOBACK-111] 구단 조회 리스트뷰 추가

---

backend/apis/notifications/views.py

-  [[KBOBACK-115] 알림 조회 리스트페이지 오류 수정](https://github.com/baseball-app/kboBack/issues/115)
- notification queryset 조건 수정
-

[KBOBACK-115] 알림 조회 리스트페이지 오류 수정

---

backend/apis/users/serializers.py

- KBOBACK-114
- 나의 승요력 계산 로직 추가
- 없음

[KBOBACK-114] 나의 승요력 계산 로직 추가

---

backend/apis/auths/serializers.py
backend/apis/auths/services.py
backend/apis/auths/swagger.py

- KBOBACK-119
- apple 로그인 id_token 방식 지원하도록 수정
- 없음

[KBOBACK-119] apple 로그인 id_token 방식 지원하도록 수정

---

backend/conf/settings/dev.py
backend/conf/settings/prod.py

-  feature/125
- prod, dev settings 파일 static 설정 수정
-

[KBOBACK-125] static settings file update

---

backend/apps/users/tasks.py
backend/conf/celery.py
backend/conf/settings/base.py
backend/config_example.toml

- KBOBACK-128
- 매일 21시에 유저/티켓 현황 디스코드에 남기는 기능 추가
- 없음

[KBOBACK-128] 매일 21시에 유저/티켓 현황 디스코드에 남기는 기능 추가

---

backend/apps/admins/tasks.py
backend/conf/settings/base.py
backend/conf/settings/dev.py
backend/conf/settings/prod.py
backend/conf/urls.py

- KBOBACK-138
- 스웨거에 로그인 추가
- 없음

KBOBACK-138 스웨거에 로그인 추가
